### ISSUE TITLE
Code based on bevfusion-mit

### ISSUE THREAD

**Issue by think-twice-1218** [hht1996ok/EA-LSS#16]
您好，请问后期会开源基于bevfusion-MIT的代码吗？

**Comment by liuyuansheng624** [comment]
> 您好，请问后期会开源基于bevfusion-MIT的代码吗？

你好 请问你在bevfusion上改好了嘛

**Comment by think-twice-1218** [comment]
emm,改了depth_lss.py,没有改loss，所以效果也不好，NDS只提了0.2

**Comment by liuyuansheng624** [comment]
> emm,改了depth_lss.py,没有改loss，所以效果也不好，NDS只提了0.2

可以加您的联系方式交流下吗 我的邮箱2495692770@qq.com

**Comment by bujianyiwang** [comment]
loss有修改成功不，整体效果咋样

**Comment by think-twice-1218** [comment]
> ###
> [May 13, 2024](#issuecomment-2107359146)

没改出来，放弃这种改进思路了

**Comment by bujianyiwang** [comment]
好的，是实现难度大，还是改进空间不大？

**Comment by bujianyiwang** [comment]
> > [May 13, 2024](#issuecomment-2107359146)
> 
> 没改出来，放弃这种改进思路了

 好的，是实现难度大，还是改进空间不大？
