### ISSUE TITLE
BEVDepth Implementation

### ISSUE THREAD

**Issue by Young98CN** [hht1996ok/EA-LSS#2]
I have a confusion about Edge-aware 3D Features generation in BEVDepth inference process. How it is generated when there is only camera data

**Comment by hht1996ok** [comment]
Thank you for your attentation. In fact, for the sake of fairness, we deleted the behavior of directly putting point clouds into the network such as Gradient Multi-view Dense Depth Maps in the comparison of BEVDepth, and only retained Gradient Edge Depth Loss and Sparse Depth Loss.

**Comment by Young98CN** [comment]
Thanks for your answer. I can understand the process of Sparse Depth Loss(like BEVDepth, right?). But I still have some puzzles.

1. How to calculate Gradient Edge Depth Loss? In your paper, this loss should input multi-view edge maps G'. How it generates?
2. The input of Semantic DepthNet Module are 2D-3D Concatenate Features $F^{concat}$. How it generates?
3. Are there any learnable parameters in the Edge-aware Depth Fusion Module?

**Comment by hht1996ok** [comment]
@Young98CN  
1. Multi-view edge maps G' is the maximum gradient of Multi-view Dense Depth Maps in the four directions of up, down, left, and right. Gradient Edge Depth Loss uses Multi-view Dense Depth Maps and Predicted Depth Maps to calculate classification loss, and G' is the loss weight.
2. We merged 2D Camera Features which generate by 2D Camera Encoder and Gradient Multi-view Dense Depth Maps after downsampling layer to get 2D-3D Concatenate Features.
3. In addition to the downsampling layer, there are no other learnable parameters in the Edge-aware Depth Fusion Module, which only contains low-dimensional geometric operations.

**Comment by Young98CN** [comment]
Thanks for your detailed answer. Sorry I did not explain clearly. I want to know what the interface process is under the setting of only camera data. 

1. For A1, In your first [answer](https://github.com/hht1996ok/EA-BEV/issues/2#issuecomment-1498377329), you said that you will Gradient Multi-view Dense Depth Maps. If you do not have it, how to generate multi-view edge maps?
2. For A2, if you input Gradient Multi-view Dense Depth Maps, LiDAR feature will merge your model. Is this a fair comparison?

**Comment by hht1996ok** [comment]
When only using image information, Edge-aware Depth Fusion Module will be deleted, we only input 2D Camera Features to Semantic DepthNet Module.

**Comment by hht1996ok** [comment]
@Young98CN We have a different depth supervision loss than bevdepth. We found that the results of the bevdepth+EA-BEV experiment were wrong and will be corrected later.

**Comment by Young98CN** [comment]
That is bad news. Waiting for your update. Thank you for your patience.

**Comment by JsutCheng** [comment]
Have same question as Young98CN , So i asked whether will release the code of bevdepth. If without lidar 5% map is interesting.

**Comment by wcyjerry** [comment]
@Young98CN Hi, I'm a little confused. While we using image-only,  so we don't use EADF feature to concat into image feature (in the paper's pipeline Figure2) right?
