### ISSUE TITLE
what's the accuracy of camera pretrained model, which use depth map as input

### ISSUE THREAD

**Issue by BoomSky0416** [hht1996ok/EA-LSS#3]

**Comment by BoomSky0416** [comment]
@hht1996ok Hello, could you please answer my question?

**Comment by hht1996ok** [comment]
Hi,
    Sorry for not paying attention to your question. Taking the camera branch of bevfusion as an example, baseline mAP is 35.0%+, and after adding EA-LSS, mAP is 38%+.

**Comment by BoomSky0416** [comment]
Thank you for your reply. But my question is if gt depth map is used to generate the depth distribution estimation, and without 3d feature extraction branch. What's the accuracy of this camera model with gt depth?

**Comment by BoomSky0416** [comment]
@hht1996ok Hello, looking forward to your reply. Thanks!

**Comment by BoomSky0416** [comment]
By the way, I found one typo in your paper. what is PFD module in table 3? Is that FGD module?

**Comment by hht1996ok** [comment]
@BoomSky0416 
1. Sorry, we did not perform the experiment of overall depth map replacement, but you can refer to the qualitative evaluation in the paper.
2. Thanks for your reminding, the content in Table 3 of the paper is wrong, and we have modified it on arxiv (Figure 2 and Figure 4 have also been modified).

**Comment by BoomSky0416** [comment]
Thanks for your reply.
