### ISSUE TITLE
Nuscenes detection errors on validation set

### ISSUE THREAD

**Issue by donand** [hht1996ok/EA-LSS#5]
Hello! Thanks for the great work!

Could you please share what errors you get for Nuscenes detection on the validation set? By errors, I mean mATE, mASE, mAOE, mAVE, mAAE.

Thank you!

**Comment by hht1996ok** [comment]
The result of our EA-LSS in val set:
mAP	mATE	mASE	mAOE	mAVE	mAAE	NDS
71.24	0.2709	0.251	0.285	0.2536	0.1899	73.12

**Comment by donand** [comment]
Thank you very much for the details!
