### ISSUE TITLE
Segmentation results

### ISSUE THREAD

**Issue by ldtho** [hht1996ok/EA-LSS#9]
Hi @hht1996ok,
Thanks for the great work. I noticed that you decided not to report the segmentation result in the latest version of the paper, may I know why?
Regards

**Comment by hht1996ok** [comment]
Hi @ldtho , 
Thank you for your question. Due to the time limit and the length of the paper submission, we have to deleted the map segmentation result from the current version. In future work, we will add this task and update it to arxiv and github.

**Comment by ldtho** [comment]
Great, looking forward to that, have you got better segmentation results compared to the v1 version of the paper? or it's still similar

**Comment by hht1996ok** [comment]
Sorry, we haven't done the segmentation experiment in the new version yet, we'll work on this in our spare time (maybe next month).

**Comment by ldtho** [comment]
looking forward to that :)
